[build]
  base = "."
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
